### PR TITLE
Change title of validity check

### PR DESCRIPTION
**Pull request by JoshuaBehrens**
As discussed on scuc23

### CODE REVIEW

**Comment by pumpi** [comment]
Bildschirmfoto 2023-03-29 um 09 21 30
This is what I mean. The Naming of the button is too long 🙈

**Comment by pumpi** [comment]
Yes bot not responsive 🙈

**Comment by JoshuaBehrens** [comment]
If I just remove "compatbility"? "Update Wizard" to "Update Check"?

**Comment by pumpi** [comment]
Sounds good for me. Did you think it's clear that this is a compatibility check?

**Comment by JoshuaBehrens** [comment]
Likely not, but it is less likely understood to be a write operation and curious people might just click on it with a better feeling

**Comment by pumpi** [comment]
Ok, but let's do it 🙈

**Pull request merged**
